title: Becca's Builds
description: The home of all things from Becca's Builds Woodshop

url: http://www.beccasbuilds.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 1

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   instagram: beccasbuilds
   #github:
   twitter: beccasbuilds
   #facebook:
   email: beccasbuilds@gmail.com

#google_analytics: "UA-58263416-1"
